#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QL_Laptop")]
	public partial class QL_LaptopDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertAccount(Account instance);
    partial void UpdateAccount(Account instance);
    partial void DeleteAccount(Account instance);
    partial void InserttblMenu(tblMenu instance);
    partial void UpdatetblMenu(tblMenu instance);
    partial void DeletetblMenu(tblMenu instance);
    partial void InserttblNguoiDungNhomNguoiDung(tblNguoiDungNhomNguoiDung instance);
    partial void UpdatetblNguoiDungNhomNguoiDung(tblNguoiDungNhomNguoiDung instance);
    partial void DeletetblNguoiDungNhomNguoiDung(tblNguoiDungNhomNguoiDung instance);
    partial void InserttblNhomNguoiDung(tblNhomNguoiDung instance);
    partial void UpdatetblNhomNguoiDung(tblNhomNguoiDung instance);
    partial void DeletetblNhomNguoiDung(tblNhomNguoiDung instance);
    partial void InserttblPhanQuyen(tblPhanQuyen instance);
    partial void UpdatetblPhanQuyen(tblPhanQuyen instance);
    partial void DeletetblPhanQuyen(tblPhanQuyen instance);
    partial void InsertEmployee(Employee instance);
    partial void UpdateEmployee(Employee instance);
    partial void DeleteEmployee(Employee instance);
    partial void InsertChiTietPhieuNhap(ChiTietPhieuNhap instance);
    partial void UpdateChiTietPhieuNhap(ChiTietPhieuNhap instance);
    partial void DeleteChiTietPhieuNhap(ChiTietPhieuNhap instance);
    partial void InsertCustomer(Customer instance);
    partial void UpdateCustomer(Customer instance);
    partial void DeleteCustomer(Customer instance);
    partial void InsertDescription(Description instance);
    partial void UpdateDescription(Description instance);
    partial void DeleteDescription(Description instance);
    partial void InsertImagePrd(ImagePrd instance);
    partial void UpdateImagePrd(ImagePrd instance);
    partial void DeleteImagePrd(ImagePrd instance);
    partial void InsertPhieuNhap(PhieuNhap instance);
    partial void UpdatePhieuNhap(PhieuNhap instance);
    partial void DeletePhieuNhap(PhieuNhap instance);
    partial void InsertPhieuXuat(PhieuXuat instance);
    partial void UpdatePhieuXuat(PhieuXuat instance);
    partial void DeletePhieuXuat(PhieuXuat instance);
    partial void Insertpromotion(promotion instance);
    partial void Updatepromotion(promotion instance);
    partial void Deletepromotion(promotion instance);
    partial void InsertPromotionsGift(PromotionsGift instance);
    partial void UpdatePromotionsGift(PromotionsGift instance);
    partial void DeletePromotionsGift(PromotionsGift instance);
    partial void InsertTrademark(Trademark instance);
    partial void UpdateTrademark(Trademark instance);
    partial void DeleteTrademark(Trademark instance);
    partial void InsertProduct(Product instance);
    partial void UpdateProduct(Product instance);
    partial void DeleteProduct(Product instance);
    partial void InsertDetail(Detail instance);
    partial void UpdateDetail(Detail instance);
    partial void DeleteDetail(Detail instance);
    partial void InsertChiTietPhieuXuat(ChiTietPhieuXuat instance);
    partial void UpdateChiTietPhieuXuat(ChiTietPhieuXuat instance);
    partial void DeleteChiTietPhieuXuat(ChiTietPhieuXuat instance);
    partial void InserttblTinhThanhPho(tblTinhThanhPho instance);
    partial void UpdatetblTinhThanhPho(tblTinhThanhPho instance);
    partial void DeletetblTinhThanhPho(tblTinhThanhPho instance);
    partial void InserttblQuanHuyen(tblQuanHuyen instance);
    partial void UpdatetblQuanHuyen(tblQuanHuyen instance);
    partial void DeletetblQuanHuyen(tblQuanHuyen instance);
    partial void InserttblPhuongXa(tblPhuongXa instance);
    partial void UpdatetblPhuongXa(tblPhuongXa instance);
    partial void DeletetblPhuongXa(tblPhuongXa instance);
    #endregion
		
		public QL_LaptopDataContext() : 
				base(global::DTO.Properties.Settings.Default.QL_LaptopConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public QL_LaptopDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QL_LaptopDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QL_LaptopDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QL_LaptopDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Account> Accounts
		{
			get
			{
				return this.GetTable<Account>();
			}
		}
		
		public System.Data.Linq.Table<tblMenu> tblMenus
		{
			get
			{
				return this.GetTable<tblMenu>();
			}
		}
		
		public System.Data.Linq.Table<tblNguoiDungNhomNguoiDung> tblNguoiDungNhomNguoiDungs
		{
			get
			{
				return this.GetTable<tblNguoiDungNhomNguoiDung>();
			}
		}
		
		public System.Data.Linq.Table<tblNhomNguoiDung> tblNhomNguoiDungs
		{
			get
			{
				return this.GetTable<tblNhomNguoiDung>();
			}
		}
		
		public System.Data.Linq.Table<tblPhanQuyen> tblPhanQuyens
		{
			get
			{
				return this.GetTable<tblPhanQuyen>();
			}
		}
		
		public System.Data.Linq.Table<Employee> Employees
		{
			get
			{
				return this.GetTable<Employee>();
			}
		}
		
		public System.Data.Linq.Table<ChiTietPhieuNhap> ChiTietPhieuNhaps
		{
			get
			{
				return this.GetTable<ChiTietPhieuNhap>();
			}
		}
		
		public System.Data.Linq.Table<Customer> Customers
		{
			get
			{
				return this.GetTable<Customer>();
			}
		}
		
		public System.Data.Linq.Table<Description> Descriptions
		{
			get
			{
				return this.GetTable<Description>();
			}
		}
		
		public System.Data.Linq.Table<ImagePrd> ImagePrds
		{
			get
			{
				return this.GetTable<ImagePrd>();
			}
		}
		
		public System.Data.Linq.Table<PhieuNhap> PhieuNhaps
		{
			get
			{
				return this.GetTable<PhieuNhap>();
			}
		}
		
		public System.Data.Linq.Table<PhieuXuat> PhieuXuats
		{
			get
			{
				return this.GetTable<PhieuXuat>();
			}
		}
		
		public System.Data.Linq.Table<promotion> promotions
		{
			get
			{
				return this.GetTable<promotion>();
			}
		}
		
		public System.Data.Linq.Table<PromotionsGift> PromotionsGifts
		{
			get
			{
				return this.GetTable<PromotionsGift>();
			}
		}
		
		public System.Data.Linq.Table<Trademark> Trademarks
		{
			get
			{
				return this.GetTable<Trademark>();
			}
		}
		
		public System.Data.Linq.Table<Product> Products
		{
			get
			{
				return this.GetTable<Product>();
			}
		}
		
		public System.Data.Linq.Table<Detail> Details
		{
			get
			{
				return this.GetTable<Detail>();
			}
		}
		
		public System.Data.Linq.Table<ChiTietPhieuXuat> ChiTietPhieuXuats
		{
			get
			{
				return this.GetTable<ChiTietPhieuXuat>();
			}
		}
		
		public System.Data.Linq.Table<tblTinhThanhPho> tblTinhThanhPhos
		{
			get
			{
				return this.GetTable<tblTinhThanhPho>();
			}
		}
		
		public System.Data.Linq.Table<tblQuanHuyen> tblQuanHuyens
		{
			get
			{
				return this.GetTable<tblQuanHuyen>();
			}
		}
		
		public System.Data.Linq.Table<tblPhuongXa> tblPhuongXas
		{
			get
			{
				return this.GetTable<tblPhuongXa>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Account")]
	public partial class Account : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _username;
		
		private string _password;
		
		private System.Nullable<int> _account_type;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void Onaccount_typeChanging(System.Nullable<int> value);
    partial void Onaccount_typeChanged();
    #endregion
		
		public Account()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="NVarChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this.OnusernameChanging(value);
					this.SendPropertyChanging();
					this._username = value;
					this.SendPropertyChanged("username");
					this.OnusernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="Char(32)")]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_account_type", DbType="Int")]
		public System.Nullable<int> account_type
		{
			get
			{
				return this._account_type;
			}
			set
			{
				if ((this._account_type != value))
				{
					this.Onaccount_typeChanging(value);
					this.SendPropertyChanging();
					this._account_type = value;
					this.SendPropertyChanged("account_type");
					this.Onaccount_typeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblMenu")]
	public partial class tblMenu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaMenu;
		
		private string _TenMenu;
		
		private string _ParentMenu;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaMenuChanging(string value);
    partial void OnMaMenuChanged();
    partial void OnTenMenuChanging(string value);
    partial void OnTenMenuChanged();
    partial void OnParentMenuChanging(string value);
    partial void OnParentMenuChanged();
    #endregion
		
		public tblMenu()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaMenu", DbType="NVarChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaMenu
		{
			get
			{
				return this._MaMenu;
			}
			set
			{
				if ((this._MaMenu != value))
				{
					this.OnMaMenuChanging(value);
					this.SendPropertyChanging();
					this._MaMenu = value;
					this.SendPropertyChanged("MaMenu");
					this.OnMaMenuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenMenu", DbType="NVarChar(1000)")]
		public string TenMenu
		{
			get
			{
				return this._TenMenu;
			}
			set
			{
				if ((this._TenMenu != value))
				{
					this.OnTenMenuChanging(value);
					this.SendPropertyChanging();
					this._TenMenu = value;
					this.SendPropertyChanged("TenMenu");
					this.OnTenMenuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParentMenu", DbType="NVarChar(100)")]
		public string ParentMenu
		{
			get
			{
				return this._ParentMenu;
			}
			set
			{
				if ((this._ParentMenu != value))
				{
					this.OnParentMenuChanging(value);
					this.SendPropertyChanging();
					this._ParentMenu = value;
					this.SendPropertyChanged("ParentMenu");
					this.OnParentMenuChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblNguoiDungNhomNguoiDung")]
	public partial class tblNguoiDungNhomNguoiDung : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _username;
		
		private string _MaNhomNguoiDung;
		
		private string _GhiChu;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    partial void OnMaNhomNguoiDungChanging(string value);
    partial void OnMaNhomNguoiDungChanged();
    partial void OnGhiChuChanging(string value);
    partial void OnGhiChuChanged();
    #endregion
		
		public tblNguoiDungNhomNguoiDung()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="NVarChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this.OnusernameChanging(value);
					this.SendPropertyChanging();
					this._username = value;
					this.SendPropertyChanged("username");
					this.OnusernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNhomNguoiDung", DbType="NVarChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaNhomNguoiDung
		{
			get
			{
				return this._MaNhomNguoiDung;
			}
			set
			{
				if ((this._MaNhomNguoiDung != value))
				{
					this.OnMaNhomNguoiDungChanging(value);
					this.SendPropertyChanging();
					this._MaNhomNguoiDung = value;
					this.SendPropertyChanged("MaNhomNguoiDung");
					this.OnMaNhomNguoiDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NVarChar(1000)")]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this.OnGhiChuChanging(value);
					this.SendPropertyChanging();
					this._GhiChu = value;
					this.SendPropertyChanged("GhiChu");
					this.OnGhiChuChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblNhomNguoiDung")]
	public partial class tblNhomNguoiDung : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaNhom;
		
		private string _TenNhom;
		
		private string _GhiChu;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNhomChanging(string value);
    partial void OnMaNhomChanged();
    partial void OnTenNhomChanging(string value);
    partial void OnTenNhomChanged();
    partial void OnGhiChuChanging(string value);
    partial void OnGhiChuChanged();
    #endregion
		
		public tblNhomNguoiDung()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNhom", DbType="NVarChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaNhom
		{
			get
			{
				return this._MaNhom;
			}
			set
			{
				if ((this._MaNhom != value))
				{
					this.OnMaNhomChanging(value);
					this.SendPropertyChanging();
					this._MaNhom = value;
					this.SendPropertyChanged("MaNhom");
					this.OnMaNhomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNhom", DbType="Char(32)")]
		public string TenNhom
		{
			get
			{
				return this._TenNhom;
			}
			set
			{
				if ((this._TenNhom != value))
				{
					this.OnTenNhomChanging(value);
					this.SendPropertyChanging();
					this._TenNhom = value;
					this.SendPropertyChanged("TenNhom");
					this.OnTenNhomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NVarChar(MAX)")]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this.OnGhiChuChanging(value);
					this.SendPropertyChanging();
					this._GhiChu = value;
					this.SendPropertyChanged("GhiChu");
					this.OnGhiChuChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblPhanQuyen")]
	public partial class tblPhanQuyen : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaNhomNguoiDung;
		
		private string _MaMenu;
		
		private System.Nullable<bool> _CoQuyen;
		
		private System.Nullable<System.DateTime> _setTime;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNhomNguoiDungChanging(string value);
    partial void OnMaNhomNguoiDungChanged();
    partial void OnMaMenuChanging(string value);
    partial void OnMaMenuChanged();
    partial void OnCoQuyenChanging(System.Nullable<bool> value);
    partial void OnCoQuyenChanged();
    partial void OnsetTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnsetTimeChanged();
    #endregion
		
		public tblPhanQuyen()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNhomNguoiDung", DbType="NVarChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaNhomNguoiDung
		{
			get
			{
				return this._MaNhomNguoiDung;
			}
			set
			{
				if ((this._MaNhomNguoiDung != value))
				{
					this.OnMaNhomNguoiDungChanging(value);
					this.SendPropertyChanging();
					this._MaNhomNguoiDung = value;
					this.SendPropertyChanged("MaNhomNguoiDung");
					this.OnMaNhomNguoiDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaMenu", DbType="NVarChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaMenu
		{
			get
			{
				return this._MaMenu;
			}
			set
			{
				if ((this._MaMenu != value))
				{
					this.OnMaMenuChanging(value);
					this.SendPropertyChanging();
					this._MaMenu = value;
					this.SendPropertyChanged("MaMenu");
					this.OnMaMenuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CoQuyen", DbType="Bit")]
		public System.Nullable<bool> CoQuyen
		{
			get
			{
				return this._CoQuyen;
			}
			set
			{
				if ((this._CoQuyen != value))
				{
					this.OnCoQuyenChanging(value);
					this.SendPropertyChanging();
					this._CoQuyen = value;
					this.SendPropertyChanged("CoQuyen");
					this.OnCoQuyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_setTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> setTime
		{
			get
			{
				return this._setTime;
			}
			set
			{
				if ((this._setTime != value))
				{
					this.OnsetTimeChanging(value);
					this.SendPropertyChanging();
					this._setTime = value;
					this.SendPropertyChanged("setTime");
					this.OnsetTimeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Employees")]
	public partial class Employee : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _id;
		
		private string _name;
		
		private System.Nullable<System.DateTime> _birthday;
		
		private string _gender;
		
		private string _phone;
		
		private string _email;
		
		private string _cmnd;
		
		private System.Nullable<decimal> _salary;
		
		private string _avatar;
		
		private System.Nullable<System.DateTime> _hire_date;
		
		private string _username;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(string value);
    partial void OnidChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnbirthdayChanging(System.Nullable<System.DateTime> value);
    partial void OnbirthdayChanged();
    partial void OngenderChanging(string value);
    partial void OngenderChanged();
    partial void OnphoneChanging(string value);
    partial void OnphoneChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OncmndChanging(string value);
    partial void OncmndChanged();
    partial void OnsalaryChanging(System.Nullable<decimal> value);
    partial void OnsalaryChanged();
    partial void OnavatarChanging(string value);
    partial void OnavatarChanged();
    partial void Onhire_dateChanging(System.Nullable<System.DateTime> value);
    partial void Onhire_dateChanged();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    #endregion
		
		public Employee()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Char(16) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(1000)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_birthday", DbType="Date")]
		public System.Nullable<System.DateTime> birthday
		{
			get
			{
				return this._birthday;
			}
			set
			{
				if ((this._birthday != value))
				{
					this.OnbirthdayChanging(value);
					this.SendPropertyChanging();
					this._birthday = value;
					this.SendPropertyChanged("birthday");
					this.OnbirthdayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gender", DbType="NVarChar(4)")]
		public string gender
		{
			get
			{
				return this._gender;
			}
			set
			{
				if ((this._gender != value))
				{
					this.OngenderChanging(value);
					this.SendPropertyChanging();
					this._gender = value;
					this.SendPropertyChanged("gender");
					this.OngenderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phone", DbType="NVarChar(100)")]
		public string phone
		{
			get
			{
				return this._phone;
			}
			set
			{
				if ((this._phone != value))
				{
					this.OnphoneChanging(value);
					this.SendPropertyChanging();
					this._phone = value;
					this.SendPropertyChanged("phone");
					this.OnphoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(100)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cmnd", DbType="NVarChar(100)")]
		public string cmnd
		{
			get
			{
				return this._cmnd;
			}
			set
			{
				if ((this._cmnd != value))
				{
					this.OncmndChanging(value);
					this.SendPropertyChanging();
					this._cmnd = value;
					this.SendPropertyChanged("cmnd");
					this.OncmndChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_salary", DbType="Decimal(32,0)")]
		public System.Nullable<decimal> salary
		{
			get
			{
				return this._salary;
			}
			set
			{
				if ((this._salary != value))
				{
					this.OnsalaryChanging(value);
					this.SendPropertyChanging();
					this._salary = value;
					this.SendPropertyChanged("salary");
					this.OnsalaryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_avatar", DbType="NVarChar(1000)")]
		public string avatar
		{
			get
			{
				return this._avatar;
			}
			set
			{
				if ((this._avatar != value))
				{
					this.OnavatarChanging(value);
					this.SendPropertyChanging();
					this._avatar = value;
					this.SendPropertyChanged("avatar");
					this.OnavatarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hire_date", DbType="Date")]
		public System.Nullable<System.DateTime> hire_date
		{
			get
			{
				return this._hire_date;
			}
			set
			{
				if ((this._hire_date != value))
				{
					this.Onhire_dateChanging(value);
					this.SendPropertyChanging();
					this._hire_date = value;
					this.SendPropertyChanged("hire_date");
					this.Onhire_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="NVarChar(100)")]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this.OnusernameChanging(value);
					this.SendPropertyChanging();
					this._username = value;
					this.SendPropertyChanged("username");
					this.OnusernameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ChiTietPhieuNhap")]
	public partial class ChiTietPhieuNhap : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _PhieuNhap_id;
		
		private string _product_id;
		
		private System.Nullable<int> _quanlity;
		
		private System.Nullable<long> _price_Import;
		
		private System.Nullable<decimal> _ratio;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPhieuNhap_idChanging(string value);
    partial void OnPhieuNhap_idChanged();
    partial void Onproduct_idChanging(string value);
    partial void Onproduct_idChanged();
    partial void OnquanlityChanging(System.Nullable<int> value);
    partial void OnquanlityChanged();
    partial void Onprice_ImportChanging(System.Nullable<long> value);
    partial void Onprice_ImportChanged();
    partial void OnratioChanging(System.Nullable<decimal> value);
    partial void OnratioChanged();
    #endregion
		
		public ChiTietPhieuNhap()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhieuNhap_id", DbType="Char(16) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string PhieuNhap_id
		{
			get
			{
				return this._PhieuNhap_id;
			}
			set
			{
				if ((this._PhieuNhap_id != value))
				{
					this.OnPhieuNhap_idChanging(value);
					this.SendPropertyChanging();
					this._PhieuNhap_id = value;
					this.SendPropertyChanged("PhieuNhap_id");
					this.OnPhieuNhap_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_id", DbType="Char(9) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string product_id
		{
			get
			{
				return this._product_id;
			}
			set
			{
				if ((this._product_id != value))
				{
					this.Onproduct_idChanging(value);
					this.SendPropertyChanging();
					this._product_id = value;
					this.SendPropertyChanged("product_id");
					this.Onproduct_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quanlity", DbType="Int")]
		public System.Nullable<int> quanlity
		{
			get
			{
				return this._quanlity;
			}
			set
			{
				if ((this._quanlity != value))
				{
					this.OnquanlityChanging(value);
					this.SendPropertyChanging();
					this._quanlity = value;
					this.SendPropertyChanged("quanlity");
					this.OnquanlityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_price_Import", DbType="BigInt")]
		public System.Nullable<long> price_Import
		{
			get
			{
				return this._price_Import;
			}
			set
			{
				if ((this._price_Import != value))
				{
					this.Onprice_ImportChanging(value);
					this.SendPropertyChanging();
					this._price_Import = value;
					this.SendPropertyChanged("price_Import");
					this.Onprice_ImportChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ratio", DbType="Decimal(32,0)")]
		public System.Nullable<decimal> ratio
		{
			get
			{
				return this._ratio;
			}
			set
			{
				if ((this._ratio != value))
				{
					this.OnratioChanging(value);
					this.SendPropertyChanging();
					this._ratio = value;
					this.SendPropertyChanged("ratio");
					this.OnratioChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Customer")]
	public partial class Customer : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _id;
		
		private string _name;
		
		private System.Nullable<System.DateTime> _birthday;
		
		private string _gender;
		
		private string _phone;
		
		private string _email;
		
		private string _cmnd;
		
		private string _avatar;
		
		private System.Nullable<int> _countProducts;
		
		private System.Nullable<decimal> _totalMoney;
		
		private string _username;
		
		private string _Address;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(string value);
    partial void OnidChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnbirthdayChanging(System.Nullable<System.DateTime> value);
    partial void OnbirthdayChanged();
    partial void OngenderChanging(string value);
    partial void OngenderChanged();
    partial void OnphoneChanging(string value);
    partial void OnphoneChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OncmndChanging(string value);
    partial void OncmndChanged();
    partial void OnavatarChanging(string value);
    partial void OnavatarChanged();
    partial void OncountProductsChanging(System.Nullable<int> value);
    partial void OncountProductsChanged();
    partial void OntotalMoneyChanging(System.Nullable<decimal> value);
    partial void OntotalMoneyChanged();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    partial void OnAddressChanging(string value);
    partial void OnAddressChanged();
    #endregion
		
		public Customer()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Char(12) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(1000)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_birthday", DbType="Date")]
		public System.Nullable<System.DateTime> birthday
		{
			get
			{
				return this._birthday;
			}
			set
			{
				if ((this._birthday != value))
				{
					this.OnbirthdayChanging(value);
					this.SendPropertyChanging();
					this._birthday = value;
					this.SendPropertyChanged("birthday");
					this.OnbirthdayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gender", DbType="NVarChar(4)")]
		public string gender
		{
			get
			{
				return this._gender;
			}
			set
			{
				if ((this._gender != value))
				{
					this.OngenderChanging(value);
					this.SendPropertyChanging();
					this._gender = value;
					this.SendPropertyChanged("gender");
					this.OngenderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phone", DbType="NVarChar(100)")]
		public string phone
		{
			get
			{
				return this._phone;
			}
			set
			{
				if ((this._phone != value))
				{
					this.OnphoneChanging(value);
					this.SendPropertyChanging();
					this._phone = value;
					this.SendPropertyChanged("phone");
					this.OnphoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(100)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cmnd", DbType="NVarChar(100)")]
		public string cmnd
		{
			get
			{
				return this._cmnd;
			}
			set
			{
				if ((this._cmnd != value))
				{
					this.OncmndChanging(value);
					this.SendPropertyChanging();
					this._cmnd = value;
					this.SendPropertyChanged("cmnd");
					this.OncmndChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_avatar", DbType="NVarChar(1000)")]
		public string avatar
		{
			get
			{
				return this._avatar;
			}
			set
			{
				if ((this._avatar != value))
				{
					this.OnavatarChanging(value);
					this.SendPropertyChanging();
					this._avatar = value;
					this.SendPropertyChanged("avatar");
					this.OnavatarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_countProducts", DbType="Int")]
		public System.Nullable<int> countProducts
		{
			get
			{
				return this._countProducts;
			}
			set
			{
				if ((this._countProducts != value))
				{
					this.OncountProductsChanging(value);
					this.SendPropertyChanging();
					this._countProducts = value;
					this.SendPropertyChanged("countProducts");
					this.OncountProductsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_totalMoney", DbType="Decimal(32,0)")]
		public System.Nullable<decimal> totalMoney
		{
			get
			{
				return this._totalMoney;
			}
			set
			{
				if ((this._totalMoney != value))
				{
					this.OntotalMoneyChanging(value);
					this.SendPropertyChanging();
					this._totalMoney = value;
					this.SendPropertyChanged("totalMoney");
					this.OntotalMoneyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="NVarChar(100)")]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this.OnusernameChanging(value);
					this.SendPropertyChanging();
					this._username = value;
					this.SendPropertyChanged("username");
					this.OnusernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="NVarChar(3000)")]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this.OnAddressChanging(value);
					this.SendPropertyChanging();
					this._Address = value;
					this.SendPropertyChanged("Address");
					this.OnAddressChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Description")]
	public partial class Description : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _product_id;
		
		private string _title;
		
		private string _content;
		
		private string _image_;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onproduct_idChanging(string value);
    partial void Onproduct_idChanged();
    partial void OntitleChanging(string value);
    partial void OntitleChanged();
    partial void OncontentChanging(string value);
    partial void OncontentChanged();
    partial void Onimage_Changing(string value);
    partial void Onimage_Changed();
    #endregion
		
		public Description()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_id", DbType="Char(9) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string product_id
		{
			get
			{
				return this._product_id;
			}
			set
			{
				if ((this._product_id != value))
				{
					this.Onproduct_idChanging(value);
					this.SendPropertyChanging();
					this._product_id = value;
					this.SendPropertyChanged("product_id");
					this.Onproduct_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_title", DbType="NVarChar(1000)")]
		public string title
		{
			get
			{
				return this._title;
			}
			set
			{
				if ((this._title != value))
				{
					this.OntitleChanging(value);
					this.SendPropertyChanging();
					this._title = value;
					this.SendPropertyChanged("title");
					this.OntitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_content", DbType="NVarChar(4000)")]
		public string content
		{
			get
			{
				return this._content;
			}
			set
			{
				if ((this._content != value))
				{
					this.OncontentChanging(value);
					this.SendPropertyChanging();
					this._content = value;
					this.SendPropertyChanged("content");
					this.OncontentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_image_", DbType="NVarChar(1000)")]
		public string image_
		{
			get
			{
				return this._image_;
			}
			set
			{
				if ((this._image_ != value))
				{
					this.Onimage_Changing(value);
					this.SendPropertyChanging();
					this._image_ = value;
					this.SendPropertyChanged("image_");
					this.Onimage_Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Image")]
	public partial class ImagePrd : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _product_id;
		
		private string _image_;
		
		private System.Nullable<bool> _active;
		
		private System.Nullable<System.DateTime> _dateUpdate;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onproduct_idChanging(string value);
    partial void Onproduct_idChanged();
    partial void Onimage_Changing(string value);
    partial void Onimage_Changed();
    partial void OnactiveChanging(System.Nullable<bool> value);
    partial void OnactiveChanged();
    partial void OndateUpdateChanging(System.Nullable<System.DateTime> value);
    partial void OndateUpdateChanged();
    #endregion
		
		public ImagePrd()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_id", DbType="Char(9) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string product_id
		{
			get
			{
				return this._product_id;
			}
			set
			{
				if ((this._product_id != value))
				{
					this.Onproduct_idChanging(value);
					this.SendPropertyChanging();
					this._product_id = value;
					this.SendPropertyChanged("product_id");
					this.Onproduct_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_image_", DbType="NVarChar(1000) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string image_
		{
			get
			{
				return this._image_;
			}
			set
			{
				if ((this._image_ != value))
				{
					this.Onimage_Changing(value);
					this.SendPropertyChanging();
					this._image_ = value;
					this.SendPropertyChanged("image_");
					this.Onimage_Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_active", DbType="Bit")]
		public System.Nullable<bool> active
		{
			get
			{
				return this._active;
			}
			set
			{
				if ((this._active != value))
				{
					this.OnactiveChanging(value);
					this.SendPropertyChanging();
					this._active = value;
					this.SendPropertyChanged("active");
					this.OnactiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dateUpdate", DbType="DateTime")]
		public System.Nullable<System.DateTime> dateUpdate
		{
			get
			{
				return this._dateUpdate;
			}
			set
			{
				if ((this._dateUpdate != value))
				{
					this.OndateUpdateChanging(value);
					this.SendPropertyChanging();
					this._dateUpdate = value;
					this.SendPropertyChanged("dateUpdate");
					this.OndateUpdateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PhieuNhap")]
	public partial class PhieuNhap : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _id;
		
		private string _employee_id;
		
		private System.Nullable<System.DateTime> _date_;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(string value);
    partial void OnidChanged();
    partial void Onemployee_idChanging(string value);
    partial void Onemployee_idChanged();
    partial void Ondate_Changing(System.Nullable<System.DateTime> value);
    partial void Ondate_Changed();
    #endregion
		
		public PhieuNhap()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Char(16) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_employee_id", DbType="Char(16)")]
		public string employee_id
		{
			get
			{
				return this._employee_id;
			}
			set
			{
				if ((this._employee_id != value))
				{
					this.Onemployee_idChanging(value);
					this.SendPropertyChanging();
					this._employee_id = value;
					this.SendPropertyChanged("employee_id");
					this.Onemployee_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date_", DbType="DateTime")]
		public System.Nullable<System.DateTime> date_
		{
			get
			{
				return this._date_;
			}
			set
			{
				if ((this._date_ != value))
				{
					this.Ondate_Changing(value);
					this.SendPropertyChanging();
					this._date_ = value;
					this.SendPropertyChanged("date_");
					this.Ondate_Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PhieuXuat")]
	public partial class PhieuXuat : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _id;
		
		private string _employee_id;
		
		private string _customer_id;
		
		private System.Nullable<System.DateTime> _date_;
		
		private System.Nullable<decimal> _total;
		
		private string _Address_;
		
		private System.Nullable<int> _status;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(string value);
    partial void OnidChanged();
    partial void Onemployee_idChanging(string value);
    partial void Onemployee_idChanged();
    partial void Oncustomer_idChanging(string value);
    partial void Oncustomer_idChanged();
    partial void Ondate_Changing(System.Nullable<System.DateTime> value);
    partial void Ondate_Changed();
    partial void OntotalChanging(System.Nullable<decimal> value);
    partial void OntotalChanged();
    partial void OnAddress_Changing(string value);
    partial void OnAddress_Changed();
    partial void OnstatusChanging(System.Nullable<int> value);
    partial void OnstatusChanged();
    #endregion
		
		public PhieuXuat()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Char(16) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_employee_id", DbType="Char(16)")]
		public string employee_id
		{
			get
			{
				return this._employee_id;
			}
			set
			{
				if ((this._employee_id != value))
				{
					this.Onemployee_idChanging(value);
					this.SendPropertyChanging();
					this._employee_id = value;
					this.SendPropertyChanged("employee_id");
					this.Onemployee_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_customer_id", DbType="Char(12)")]
		public string customer_id
		{
			get
			{
				return this._customer_id;
			}
			set
			{
				if ((this._customer_id != value))
				{
					this.Oncustomer_idChanging(value);
					this.SendPropertyChanging();
					this._customer_id = value;
					this.SendPropertyChanged("customer_id");
					this.Oncustomer_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date_", DbType="DateTime")]
		public System.Nullable<System.DateTime> date_
		{
			get
			{
				return this._date_;
			}
			set
			{
				if ((this._date_ != value))
				{
					this.Ondate_Changing(value);
					this.SendPropertyChanging();
					this._date_ = value;
					this.SendPropertyChanged("date_");
					this.Ondate_Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_total", DbType="Decimal(32,0)")]
		public System.Nullable<decimal> total
		{
			get
			{
				return this._total;
			}
			set
			{
				if ((this._total != value))
				{
					this.OntotalChanging(value);
					this.SendPropertyChanging();
					this._total = value;
					this.SendPropertyChanged("total");
					this.OntotalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address_", DbType="NVarChar(3000)")]
		public string Address_
		{
			get
			{
				return this._Address_;
			}
			set
			{
				if ((this._Address_ != value))
				{
					this.OnAddress_Changing(value);
					this.SendPropertyChanging();
					this._Address_ = value;
					this.SendPropertyChanged("Address_");
					this.OnAddress_Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="Int")]
		public System.Nullable<int> status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.promotions")]
	public partial class promotion : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _product_id;
		
		private System.DateTime _date_start;
		
		private System.Nullable<System.DateTime> _date_end;
		
		private System.Nullable<decimal> _price;
		
		private System.Nullable<decimal> _price_after;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onproduct_idChanging(string value);
    partial void Onproduct_idChanged();
    partial void Ondate_startChanging(System.DateTime value);
    partial void Ondate_startChanged();
    partial void Ondate_endChanging(System.Nullable<System.DateTime> value);
    partial void Ondate_endChanged();
    partial void OnpriceChanging(System.Nullable<decimal> value);
    partial void OnpriceChanged();
    partial void Onprice_afterChanging(System.Nullable<decimal> value);
    partial void Onprice_afterChanged();
    #endregion
		
		public promotion()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_id", DbType="Char(9) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string product_id
		{
			get
			{
				return this._product_id;
			}
			set
			{
				if ((this._product_id != value))
				{
					this.Onproduct_idChanging(value);
					this.SendPropertyChanging();
					this._product_id = value;
					this.SendPropertyChanged("product_id");
					this.Onproduct_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date_start", DbType="Date NOT NULL", IsPrimaryKey=true)]
		public System.DateTime date_start
		{
			get
			{
				return this._date_start;
			}
			set
			{
				if ((this._date_start != value))
				{
					this.Ondate_startChanging(value);
					this.SendPropertyChanging();
					this._date_start = value;
					this.SendPropertyChanged("date_start");
					this.Ondate_startChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date_end", DbType="Date")]
		public System.Nullable<System.DateTime> date_end
		{
			get
			{
				return this._date_end;
			}
			set
			{
				if ((this._date_end != value))
				{
					this.Ondate_endChanging(value);
					this.SendPropertyChanging();
					this._date_end = value;
					this.SendPropertyChanged("date_end");
					this.Ondate_endChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_price", DbType="Decimal(32,0)")]
		public System.Nullable<decimal> price
		{
			get
			{
				return this._price;
			}
			set
			{
				if ((this._price != value))
				{
					this.OnpriceChanging(value);
					this.SendPropertyChanging();
					this._price = value;
					this.SendPropertyChanged("price");
					this.OnpriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_price_after", DbType="Decimal(32,0)")]
		public System.Nullable<decimal> price_after
		{
			get
			{
				return this._price_after;
			}
			set
			{
				if ((this._price_after != value))
				{
					this.Onprice_afterChanging(value);
					this.SendPropertyChanging();
					this._price_after = value;
					this.SendPropertyChanged("price_after");
					this.Onprice_afterChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PromotionsGift")]
	public partial class PromotionsGift : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _product_id;
		
		private string _gift1;
		
		private string _gift2;
		
		private string _gift3;
		
		private string _gift4;
		
		private System.Nullable<decimal> _priceSum;
		
		private System.Nullable<System.DateTime> _date_start;
		
		private System.Nullable<System.DateTime> _date_end;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onproduct_idChanging(string value);
    partial void Onproduct_idChanged();
    partial void Ongift1Changing(string value);
    partial void Ongift1Changed();
    partial void Ongift2Changing(string value);
    partial void Ongift2Changed();
    partial void Ongift3Changing(string value);
    partial void Ongift3Changed();
    partial void Ongift4Changing(string value);
    partial void Ongift4Changed();
    partial void OnpriceSumChanging(System.Nullable<decimal> value);
    partial void OnpriceSumChanged();
    partial void Ondate_startChanging(System.Nullable<System.DateTime> value);
    partial void Ondate_startChanged();
    partial void Ondate_endChanging(System.Nullable<System.DateTime> value);
    partial void Ondate_endChanged();
    #endregion
		
		public PromotionsGift()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_id", DbType="Char(9) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string product_id
		{
			get
			{
				return this._product_id;
			}
			set
			{
				if ((this._product_id != value))
				{
					this.Onproduct_idChanging(value);
					this.SendPropertyChanging();
					this._product_id = value;
					this.SendPropertyChanged("product_id");
					this.Onproduct_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gift1", DbType="NVarChar(1000)")]
		public string gift1
		{
			get
			{
				return this._gift1;
			}
			set
			{
				if ((this._gift1 != value))
				{
					this.Ongift1Changing(value);
					this.SendPropertyChanging();
					this._gift1 = value;
					this.SendPropertyChanged("gift1");
					this.Ongift1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gift2", DbType="NVarChar(1000)")]
		public string gift2
		{
			get
			{
				return this._gift2;
			}
			set
			{
				if ((this._gift2 != value))
				{
					this.Ongift2Changing(value);
					this.SendPropertyChanging();
					this._gift2 = value;
					this.SendPropertyChanged("gift2");
					this.Ongift2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gift3", DbType="NVarChar(1000)")]
		public string gift3
		{
			get
			{
				return this._gift3;
			}
			set
			{
				if ((this._gift3 != value))
				{
					this.Ongift3Changing(value);
					this.SendPropertyChanging();
					this._gift3 = value;
					this.SendPropertyChanged("gift3");
					this.Ongift3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gift4", DbType="NVarChar(1000)")]
		public string gift4
		{
			get
			{
				return this._gift4;
			}
			set
			{
				if ((this._gift4 != value))
				{
					this.Ongift4Changing(value);
					this.SendPropertyChanging();
					this._gift4 = value;
					this.SendPropertyChanged("gift4");
					this.Ongift4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_priceSum", DbType="Decimal(32,0)")]
		public System.Nullable<decimal> priceSum
		{
			get
			{
				return this._priceSum;
			}
			set
			{
				if ((this._priceSum != value))
				{
					this.OnpriceSumChanging(value);
					this.SendPropertyChanging();
					this._priceSum = value;
					this.SendPropertyChanged("priceSum");
					this.OnpriceSumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date_start", DbType="Date")]
		public System.Nullable<System.DateTime> date_start
		{
			get
			{
				return this._date_start;
			}
			set
			{
				if ((this._date_start != value))
				{
					this.Ondate_startChanging(value);
					this.SendPropertyChanging();
					this._date_start = value;
					this.SendPropertyChanged("date_start");
					this.Ondate_startChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date_end", DbType="Date")]
		public System.Nullable<System.DateTime> date_end
		{
			get
			{
				return this._date_end;
			}
			set
			{
				if ((this._date_end != value))
				{
					this.Ondate_endChanging(value);
					this.SendPropertyChanging();
					this._date_end = value;
					this.SendPropertyChanged("date_end");
					this.Ondate_endChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Trademark")]
	public partial class Trademark : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _name;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    #endregion
		
		public Trademark()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(1000)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Products")]
	public partial class Product : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _id;
		
		private string _Name;
		
		private System.Nullable<int> _quanlity;
		
		private System.Nullable<int> _purchase;
		
		private System.Nullable<decimal> _price;
		
		private System.Nullable<int> _trademark_id;
		
		private string _avatar;
		
		private System.Nullable<int> _view_;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(string value);
    partial void OnidChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnquanlityChanging(System.Nullable<int> value);
    partial void OnquanlityChanged();
    partial void OnpurchaseChanging(System.Nullable<int> value);
    partial void OnpurchaseChanged();
    partial void OnpriceChanging(System.Nullable<decimal> value);
    partial void OnpriceChanged();
    partial void Ontrademark_idChanging(System.Nullable<int> value);
    partial void Ontrademark_idChanged();
    partial void OnavatarChanging(string value);
    partial void OnavatarChanged();
    partial void Onview_Changing(System.Nullable<int> value);
    partial void Onview_Changed();
    #endregion
		
		public Product()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Char(9) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(1000)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quanlity", DbType="Int")]
		public System.Nullable<int> quanlity
		{
			get
			{
				return this._quanlity;
			}
			set
			{
				if ((this._quanlity != value))
				{
					this.OnquanlityChanging(value);
					this.SendPropertyChanging();
					this._quanlity = value;
					this.SendPropertyChanged("quanlity");
					this.OnquanlityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_purchase", DbType="Int")]
		public System.Nullable<int> purchase
		{
			get
			{
				return this._purchase;
			}
			set
			{
				if ((this._purchase != value))
				{
					this.OnpurchaseChanging(value);
					this.SendPropertyChanging();
					this._purchase = value;
					this.SendPropertyChanged("purchase");
					this.OnpurchaseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_price", DbType="Decimal(32,0)")]
		public System.Nullable<decimal> price
		{
			get
			{
				return this._price;
			}
			set
			{
				if ((this._price != value))
				{
					this.OnpriceChanging(value);
					this.SendPropertyChanging();
					this._price = value;
					this.SendPropertyChanged("price");
					this.OnpriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trademark_id", DbType="Int")]
		public System.Nullable<int> trademark_id
		{
			get
			{
				return this._trademark_id;
			}
			set
			{
				if ((this._trademark_id != value))
				{
					this.Ontrademark_idChanging(value);
					this.SendPropertyChanging();
					this._trademark_id = value;
					this.SendPropertyChanged("trademark_id");
					this.Ontrademark_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_avatar", DbType="NVarChar(1000)")]
		public string avatar
		{
			get
			{
				return this._avatar;
			}
			set
			{
				if ((this._avatar != value))
				{
					this.OnavatarChanging(value);
					this.SendPropertyChanging();
					this._avatar = value;
					this.SendPropertyChanged("avatar");
					this.OnavatarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_view_", DbType="Int")]
		public System.Nullable<int> view_
		{
			get
			{
				return this._view_;
			}
			set
			{
				if ((this._view_ != value))
				{
					this.Onview_Changing(value);
					this.SendPropertyChanging();
					this._view_ = value;
					this.SendPropertyChanged("view_");
					this.Onview_Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Detail")]
	public partial class Detail : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _product_id;
		
		private string _CPU;
		
		private string _SoNhan;
		
		private string _SoLuong;
		
		private string _Speed;
		
		private string _MaxSpeed;
		
		private string _Cache;
		
		private string _RAM;
		
		private string _RAM_type;
		
		private string _BusRAM;
		
		private string _MaxRAM;
		
		private string _OCung;
		
		private string _ManHinh;
		
		private string _DoPhanGiai;
		
		private string _TanSoQuet;
		
		private string _CongNgheManHinh;
		
		private string _VGA;
		
		private string _AmThanh;
		
		private string _CongGiaoTiep;
		
		private string _KetNoiKhongDay;
		
		private string _Webcam;
		
		private string _TinhNangKhac;
		
		private string _DenBanPhim;
		
		private string _SizeAndWeight;
		
		private string _ChatLieu;
		
		private string _Pin;
		
		private string _HeDieuHanh;
		
		private string _RaMat;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onproduct_idChanging(string value);
    partial void Onproduct_idChanged();
    partial void OnCPUChanging(string value);
    partial void OnCPUChanged();
    partial void OnSoNhanChanging(string value);
    partial void OnSoNhanChanged();
    partial void OnSoLuongChanging(string value);
    partial void OnSoLuongChanged();
    partial void OnSpeedChanging(string value);
    partial void OnSpeedChanged();
    partial void OnMaxSpeedChanging(string value);
    partial void OnMaxSpeedChanged();
    partial void OnCacheChanging(string value);
    partial void OnCacheChanged();
    partial void OnRAMChanging(string value);
    partial void OnRAMChanged();
    partial void OnRAM_typeChanging(string value);
    partial void OnRAM_typeChanged();
    partial void OnBusRAMChanging(string value);
    partial void OnBusRAMChanged();
    partial void OnMaxRAMChanging(string value);
    partial void OnMaxRAMChanged();
    partial void OnOCungChanging(string value);
    partial void OnOCungChanged();
    partial void OnManHinhChanging(string value);
    partial void OnManHinhChanged();
    partial void OnDoPhanGiaiChanging(string value);
    partial void OnDoPhanGiaiChanged();
    partial void OnTanSoQuetChanging(string value);
    partial void OnTanSoQuetChanged();
    partial void OnCongNgheManHinhChanging(string value);
    partial void OnCongNgheManHinhChanged();
    partial void OnVGAChanging(string value);
    partial void OnVGAChanged();
    partial void OnAmThanhChanging(string value);
    partial void OnAmThanhChanged();
    partial void OnCongGiaoTiepChanging(string value);
    partial void OnCongGiaoTiepChanged();
    partial void OnKetNoiKhongDayChanging(string value);
    partial void OnKetNoiKhongDayChanged();
    partial void OnWebcamChanging(string value);
    partial void OnWebcamChanged();
    partial void OnTinhNangKhacChanging(string value);
    partial void OnTinhNangKhacChanged();
    partial void OnDenBanPhimChanging(string value);
    partial void OnDenBanPhimChanged();
    partial void OnSizeAndWeightChanging(string value);
    partial void OnSizeAndWeightChanged();
    partial void OnChatLieuChanging(string value);
    partial void OnChatLieuChanged();
    partial void OnPinChanging(string value);
    partial void OnPinChanged();
    partial void OnHeDieuHanhChanging(string value);
    partial void OnHeDieuHanhChanged();
    partial void OnRaMatChanging(string value);
    partial void OnRaMatChanged();
    #endregion
		
		public Detail()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_id", DbType="Char(9)")]
		public string product_id
		{
			get
			{
				return this._product_id;
			}
			set
			{
				if ((this._product_id != value))
				{
					this.Onproduct_idChanging(value);
					this.SendPropertyChanging();
					this._product_id = value;
					this.SendPropertyChanged("product_id");
					this.Onproduct_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CPU", DbType="NVarChar(1000)")]
		public string CPU
		{
			get
			{
				return this._CPU;
			}
			set
			{
				if ((this._CPU != value))
				{
					this.OnCPUChanging(value);
					this.SendPropertyChanging();
					this._CPU = value;
					this.SendPropertyChanged("CPU");
					this.OnCPUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoNhan", DbType="NVarChar(100)")]
		public string SoNhan
		{
			get
			{
				return this._SoNhan;
			}
			set
			{
				if ((this._SoNhan != value))
				{
					this.OnSoNhanChanging(value);
					this.SendPropertyChanging();
					this._SoNhan = value;
					this.SendPropertyChanged("SoNhan");
					this.OnSoNhanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuong", DbType="NVarChar(100)")]
		public string SoLuong
		{
			get
			{
				return this._SoLuong;
			}
			set
			{
				if ((this._SoLuong != value))
				{
					this.OnSoLuongChanging(value);
					this.SendPropertyChanging();
					this._SoLuong = value;
					this.SendPropertyChanged("SoLuong");
					this.OnSoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Speed", DbType="NVarChar(1000)")]
		public string Speed
		{
			get
			{
				return this._Speed;
			}
			set
			{
				if ((this._Speed != value))
				{
					this.OnSpeedChanging(value);
					this.SendPropertyChanging();
					this._Speed = value;
					this.SendPropertyChanged("Speed");
					this.OnSpeedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaxSpeed", DbType="NVarChar(1000)")]
		public string MaxSpeed
		{
			get
			{
				return this._MaxSpeed;
			}
			set
			{
				if ((this._MaxSpeed != value))
				{
					this.OnMaxSpeedChanging(value);
					this.SendPropertyChanging();
					this._MaxSpeed = value;
					this.SendPropertyChanged("MaxSpeed");
					this.OnMaxSpeedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cache", DbType="NVarChar(1000)")]
		public string Cache
		{
			get
			{
				return this._Cache;
			}
			set
			{
				if ((this._Cache != value))
				{
					this.OnCacheChanging(value);
					this.SendPropertyChanging();
					this._Cache = value;
					this.SendPropertyChanged("Cache");
					this.OnCacheChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RAM", DbType="NVarChar(1000)")]
		public string RAM
		{
			get
			{
				return this._RAM;
			}
			set
			{
				if ((this._RAM != value))
				{
					this.OnRAMChanging(value);
					this.SendPropertyChanging();
					this._RAM = value;
					this.SendPropertyChanged("RAM");
					this.OnRAMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RAM_type", DbType="NVarChar(1000)")]
		public string RAM_type
		{
			get
			{
				return this._RAM_type;
			}
			set
			{
				if ((this._RAM_type != value))
				{
					this.OnRAM_typeChanging(value);
					this.SendPropertyChanging();
					this._RAM_type = value;
					this.SendPropertyChanged("RAM_type");
					this.OnRAM_typeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BusRAM", DbType="NVarChar(1000)")]
		public string BusRAM
		{
			get
			{
				return this._BusRAM;
			}
			set
			{
				if ((this._BusRAM != value))
				{
					this.OnBusRAMChanging(value);
					this.SendPropertyChanging();
					this._BusRAM = value;
					this.SendPropertyChanged("BusRAM");
					this.OnBusRAMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaxRAM", DbType="NVarChar(1000)")]
		public string MaxRAM
		{
			get
			{
				return this._MaxRAM;
			}
			set
			{
				if ((this._MaxRAM != value))
				{
					this.OnMaxRAMChanging(value);
					this.SendPropertyChanging();
					this._MaxRAM = value;
					this.SendPropertyChanged("MaxRAM");
					this.OnMaxRAMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OCung", DbType="NVarChar(1000)")]
		public string OCung
		{
			get
			{
				return this._OCung;
			}
			set
			{
				if ((this._OCung != value))
				{
					this.OnOCungChanging(value);
					this.SendPropertyChanging();
					this._OCung = value;
					this.SendPropertyChanged("OCung");
					this.OnOCungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ManHinh", DbType="NVarChar(1000)")]
		public string ManHinh
		{
			get
			{
				return this._ManHinh;
			}
			set
			{
				if ((this._ManHinh != value))
				{
					this.OnManHinhChanging(value);
					this.SendPropertyChanging();
					this._ManHinh = value;
					this.SendPropertyChanged("ManHinh");
					this.OnManHinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DoPhanGiai", DbType="NVarChar(1000)")]
		public string DoPhanGiai
		{
			get
			{
				return this._DoPhanGiai;
			}
			set
			{
				if ((this._DoPhanGiai != value))
				{
					this.OnDoPhanGiaiChanging(value);
					this.SendPropertyChanging();
					this._DoPhanGiai = value;
					this.SendPropertyChanged("DoPhanGiai");
					this.OnDoPhanGiaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TanSoQuet", DbType="NVarChar(1000)")]
		public string TanSoQuet
		{
			get
			{
				return this._TanSoQuet;
			}
			set
			{
				if ((this._TanSoQuet != value))
				{
					this.OnTanSoQuetChanging(value);
					this.SendPropertyChanging();
					this._TanSoQuet = value;
					this.SendPropertyChanged("TanSoQuet");
					this.OnTanSoQuetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CongNgheManHinh", DbType="NVarChar(1000)")]
		public string CongNgheManHinh
		{
			get
			{
				return this._CongNgheManHinh;
			}
			set
			{
				if ((this._CongNgheManHinh != value))
				{
					this.OnCongNgheManHinhChanging(value);
					this.SendPropertyChanging();
					this._CongNgheManHinh = value;
					this.SendPropertyChanged("CongNgheManHinh");
					this.OnCongNgheManHinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VGA", DbType="NVarChar(1000)")]
		public string VGA
		{
			get
			{
				return this._VGA;
			}
			set
			{
				if ((this._VGA != value))
				{
					this.OnVGAChanging(value);
					this.SendPropertyChanging();
					this._VGA = value;
					this.SendPropertyChanged("VGA");
					this.OnVGAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AmThanh", DbType="NVarChar(1000)")]
		public string AmThanh
		{
			get
			{
				return this._AmThanh;
			}
			set
			{
				if ((this._AmThanh != value))
				{
					this.OnAmThanhChanging(value);
					this.SendPropertyChanging();
					this._AmThanh = value;
					this.SendPropertyChanged("AmThanh");
					this.OnAmThanhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CongGiaoTiep", DbType="NVarChar(1000)")]
		public string CongGiaoTiep
		{
			get
			{
				return this._CongGiaoTiep;
			}
			set
			{
				if ((this._CongGiaoTiep != value))
				{
					this.OnCongGiaoTiepChanging(value);
					this.SendPropertyChanging();
					this._CongGiaoTiep = value;
					this.SendPropertyChanged("CongGiaoTiep");
					this.OnCongGiaoTiepChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KetNoiKhongDay", DbType="NVarChar(1000)")]
		public string KetNoiKhongDay
		{
			get
			{
				return this._KetNoiKhongDay;
			}
			set
			{
				if ((this._KetNoiKhongDay != value))
				{
					this.OnKetNoiKhongDayChanging(value);
					this.SendPropertyChanging();
					this._KetNoiKhongDay = value;
					this.SendPropertyChanged("KetNoiKhongDay");
					this.OnKetNoiKhongDayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Webcam", DbType="NVarChar(1000)")]
		public string Webcam
		{
			get
			{
				return this._Webcam;
			}
			set
			{
				if ((this._Webcam != value))
				{
					this.OnWebcamChanging(value);
					this.SendPropertyChanging();
					this._Webcam = value;
					this.SendPropertyChanged("Webcam");
					this.OnWebcamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TinhNangKhac", DbType="NVarChar(1000)")]
		public string TinhNangKhac
		{
			get
			{
				return this._TinhNangKhac;
			}
			set
			{
				if ((this._TinhNangKhac != value))
				{
					this.OnTinhNangKhacChanging(value);
					this.SendPropertyChanging();
					this._TinhNangKhac = value;
					this.SendPropertyChanged("TinhNangKhac");
					this.OnTinhNangKhacChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DenBanPhim", DbType="NVarChar(1000)")]
		public string DenBanPhim
		{
			get
			{
				return this._DenBanPhim;
			}
			set
			{
				if ((this._DenBanPhim != value))
				{
					this.OnDenBanPhimChanging(value);
					this.SendPropertyChanging();
					this._DenBanPhim = value;
					this.SendPropertyChanged("DenBanPhim");
					this.OnDenBanPhimChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SizeAndWeight", DbType="NVarChar(1000)")]
		public string SizeAndWeight
		{
			get
			{
				return this._SizeAndWeight;
			}
			set
			{
				if ((this._SizeAndWeight != value))
				{
					this.OnSizeAndWeightChanging(value);
					this.SendPropertyChanging();
					this._SizeAndWeight = value;
					this.SendPropertyChanged("SizeAndWeight");
					this.OnSizeAndWeightChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChatLieu", DbType="NVarChar(1000)")]
		public string ChatLieu
		{
			get
			{
				return this._ChatLieu;
			}
			set
			{
				if ((this._ChatLieu != value))
				{
					this.OnChatLieuChanging(value);
					this.SendPropertyChanging();
					this._ChatLieu = value;
					this.SendPropertyChanged("ChatLieu");
					this.OnChatLieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pin", DbType="NVarChar(1000)")]
		public string Pin
		{
			get
			{
				return this._Pin;
			}
			set
			{
				if ((this._Pin != value))
				{
					this.OnPinChanging(value);
					this.SendPropertyChanging();
					this._Pin = value;
					this.SendPropertyChanged("Pin");
					this.OnPinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HeDieuHanh", DbType="NVarChar(1000)")]
		public string HeDieuHanh
		{
			get
			{
				return this._HeDieuHanh;
			}
			set
			{
				if ((this._HeDieuHanh != value))
				{
					this.OnHeDieuHanhChanging(value);
					this.SendPropertyChanging();
					this._HeDieuHanh = value;
					this.SendPropertyChanged("HeDieuHanh");
					this.OnHeDieuHanhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RaMat", DbType="NVarChar(1000)")]
		public string RaMat
		{
			get
			{
				return this._RaMat;
			}
			set
			{
				if ((this._RaMat != value))
				{
					this.OnRaMatChanging(value);
					this.SendPropertyChanging();
					this._RaMat = value;
					this.SendPropertyChanged("RaMat");
					this.OnRaMatChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ChiTietPhieuXuat")]
	public partial class ChiTietPhieuXuat : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _phieuXuat_id;
		
		private string _product_id;
		
		private System.Nullable<int> _quanlity;
		
		private System.Nullable<decimal> _price;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnphieuXuat_idChanging(string value);
    partial void OnphieuXuat_idChanged();
    partial void Onproduct_idChanging(string value);
    partial void Onproduct_idChanged();
    partial void OnquanlityChanging(System.Nullable<int> value);
    partial void OnquanlityChanged();
    partial void OnpriceChanging(System.Nullable<decimal> value);
    partial void OnpriceChanged();
    #endregion
		
		public ChiTietPhieuXuat()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phieuXuat_id", DbType="Char(16) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string phieuXuat_id
		{
			get
			{
				return this._phieuXuat_id;
			}
			set
			{
				if ((this._phieuXuat_id != value))
				{
					this.OnphieuXuat_idChanging(value);
					this.SendPropertyChanging();
					this._phieuXuat_id = value;
					this.SendPropertyChanged("phieuXuat_id");
					this.OnphieuXuat_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_id", DbType="Char(9) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string product_id
		{
			get
			{
				return this._product_id;
			}
			set
			{
				if ((this._product_id != value))
				{
					this.Onproduct_idChanging(value);
					this.SendPropertyChanging();
					this._product_id = value;
					this.SendPropertyChanged("product_id");
					this.Onproduct_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quanlity", DbType="Int")]
		public System.Nullable<int> quanlity
		{
			get
			{
				return this._quanlity;
			}
			set
			{
				if ((this._quanlity != value))
				{
					this.OnquanlityChanging(value);
					this.SendPropertyChanging();
					this._quanlity = value;
					this.SendPropertyChanged("quanlity");
					this.OnquanlityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_price", DbType="Decimal(32,0)")]
		public System.Nullable<decimal> price
		{
			get
			{
				return this._price;
			}
			set
			{
				if ((this._price != value))
				{
					this.OnpriceChanging(value);
					this.SendPropertyChanging();
					this._price = value;
					this.SendPropertyChanged("price");
					this.OnpriceChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblTinhThanhPho")]
	public partial class tblTinhThanhPho : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaTinhThanhPho;
		
		private string _TenTinhThanhPho;
		
		private string _GhiChu;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaTinhThanhPhoChanging(string value);
    partial void OnMaTinhThanhPhoChanged();
    partial void OnTenTinhThanhPhoChanging(string value);
    partial void OnTenTinhThanhPhoChanged();
    partial void OnGhiChuChanging(string value);
    partial void OnGhiChuChanged();
    #endregion
		
		public tblTinhThanhPho()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTinhThanhPho", DbType="VarChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaTinhThanhPho
		{
			get
			{
				return this._MaTinhThanhPho;
			}
			set
			{
				if ((this._MaTinhThanhPho != value))
				{
					this.OnMaTinhThanhPhoChanging(value);
					this.SendPropertyChanging();
					this._MaTinhThanhPho = value;
					this.SendPropertyChanged("MaTinhThanhPho");
					this.OnMaTinhThanhPhoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenTinhThanhPho", DbType="NVarChar(500)")]
		public string TenTinhThanhPho
		{
			get
			{
				return this._TenTinhThanhPho;
			}
			set
			{
				if ((this._TenTinhThanhPho != value))
				{
					this.OnTenTinhThanhPhoChanging(value);
					this.SendPropertyChanging();
					this._TenTinhThanhPho = value;
					this.SendPropertyChanged("TenTinhThanhPho");
					this.OnTenTinhThanhPhoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NVarChar(500)")]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this.OnGhiChuChanging(value);
					this.SendPropertyChanging();
					this._GhiChu = value;
					this.SendPropertyChanged("GhiChu");
					this.OnGhiChuChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblQuanHuyen")]
	public partial class tblQuanHuyen : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaQuanHuyen;
		
		private string _MaTinhThanhPho;
		
		private string _TenQuanHuyen;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaQuanHuyenChanging(string value);
    partial void OnMaQuanHuyenChanged();
    partial void OnMaTinhThanhPhoChanging(string value);
    partial void OnMaTinhThanhPhoChanged();
    partial void OnTenQuanHuyenChanging(string value);
    partial void OnTenQuanHuyenChanged();
    #endregion
		
		public tblQuanHuyen()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaQuanHuyen", DbType="VarChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaQuanHuyen
		{
			get
			{
				return this._MaQuanHuyen;
			}
			set
			{
				if ((this._MaQuanHuyen != value))
				{
					this.OnMaQuanHuyenChanging(value);
					this.SendPropertyChanging();
					this._MaQuanHuyen = value;
					this.SendPropertyChanged("MaQuanHuyen");
					this.OnMaQuanHuyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTinhThanhPho", DbType="VarChar(100)")]
		public string MaTinhThanhPho
		{
			get
			{
				return this._MaTinhThanhPho;
			}
			set
			{
				if ((this._MaTinhThanhPho != value))
				{
					this.OnMaTinhThanhPhoChanging(value);
					this.SendPropertyChanging();
					this._MaTinhThanhPho = value;
					this.SendPropertyChanged("MaTinhThanhPho");
					this.OnMaTinhThanhPhoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenQuanHuyen", DbType="NVarChar(500)")]
		public string TenQuanHuyen
		{
			get
			{
				return this._TenQuanHuyen;
			}
			set
			{
				if ((this._TenQuanHuyen != value))
				{
					this.OnTenQuanHuyenChanging(value);
					this.SendPropertyChanging();
					this._TenQuanHuyen = value;
					this.SendPropertyChanged("TenQuanHuyen");
					this.OnTenQuanHuyenChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblPhuongXa")]
	public partial class tblPhuongXa : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaPhuongXa;
		
		private string _MaQuanHuyen;
		
		private string _TenPhuongXa;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaPhuongXaChanging(string value);
    partial void OnMaPhuongXaChanged();
    partial void OnMaQuanHuyenChanging(string value);
    partial void OnMaQuanHuyenChanged();
    partial void OnTenPhuongXaChanging(string value);
    partial void OnTenPhuongXaChanged();
    #endregion
		
		public tblPhuongXa()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPhuongXa", DbType="VarChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaPhuongXa
		{
			get
			{
				return this._MaPhuongXa;
			}
			set
			{
				if ((this._MaPhuongXa != value))
				{
					this.OnMaPhuongXaChanging(value);
					this.SendPropertyChanging();
					this._MaPhuongXa = value;
					this.SendPropertyChanged("MaPhuongXa");
					this.OnMaPhuongXaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaQuanHuyen", DbType="VarChar(100)")]
		public string MaQuanHuyen
		{
			get
			{
				return this._MaQuanHuyen;
			}
			set
			{
				if ((this._MaQuanHuyen != value))
				{
					this.OnMaQuanHuyenChanging(value);
					this.SendPropertyChanging();
					this._MaQuanHuyen = value;
					this.SendPropertyChanged("MaQuanHuyen");
					this.OnMaQuanHuyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenPhuongXa", DbType="NVarChar(500)")]
		public string TenPhuongXa
		{
			get
			{
				return this._TenPhuongXa;
			}
			set
			{
				if ((this._TenPhuongXa != value))
				{
					this.OnTenPhuongXaChanging(value);
					this.SendPropertyChanging();
					this._TenPhuongXa = value;
					this.SendPropertyChanged("TenPhuongXa");
					this.OnTenPhuongXaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
